spring:
  datasource:
    url: jdbc:h2:mem:bankdb
    driverClassName: org.h2.Driver
    username: bank
    password: bank

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
  jackson:
    default-property-inclusion: non_null